### PR TITLE
fix example and doc test

### PR DESCRIPTION
**Pull request by armenic**
Hi @dgkf,

Thanks for the awesome rust R :)
Finally had a chance to try it. Very, very cool 👍 You should certainly push the development forward. People will praise you for the performant and safe R!

I wanted to see if you have any tests and submitted `cargo test`. It threw failures with example and one doc test. This MR fixes https://github.com/armenic/R/issues/1

Do you mind if I start adding unit tests while I am learning the package?

### CODE REVIEW

**Comment by dgkf** [comment]
Thanks @armenic! Good on you for checking the testing suite! Looks like some CI is needed to keep me from going off the rails again. I tested with your changes locally and all looks good. Thanks for sorting it out.

I think I know why the CLA isn't getting picked up. Your commit is under a different account. I think you can either sign the CLA from that account or `git rebase` to modify the commit author in your fork.

**Comment by edgar-manukyan** [comment]
Good eye Doug, as always :). I signed the CLA with the other account as well and it is now green :)

CI would be awesome and I assume that you are fine with adding unit tests.

**Comment by dgkf** [comment]
> I assume that you are fine with adding unit tests.

Yeah - always appreciated, but admittedly I see the code as still quite young - young enough that unit testing might be more of an impediment than a helpful tool. For example, one of the reasons these tests for the vector module are underloved is that I'm [still debating some pretty fundamental design objectives](https://github.com/dgkf/R/issues/2) that will likely break all the testing anyways.

If you're looking for ways to contribute, at this point I would encourage instead implementing some internal functions ([`q()`](https://github.com/dgkf/R/issues/5), `cat()` or `paste()` would be good candidates, or starting to replace `unimplemented!()` calls with error conditions)

**Comment by edgar-manukyan** [comment]
Sounds good Doug, will do as you suggested.

**Pull request merged**
